package module.backmutpres;

import java.awt.BorderLayout;
import java.util.List;

import egps2.frame.ModuleFace;
import egps2.modulei.IInformation;
import egps2.modulei.IModuleLoader;


@SuppressWarnings("serial")
public class GuiMain extends ModuleFace{
	
	protected SimplestModuleController controller = new SimplestModuleController();
	
	WorkBanch4presenter comp = new WorkBanch4presenter(this);
	
	protected GuiMain(IModuleLoader moduleLoader) {
		super(moduleLoader);
		
		setLayout(new BorderLayout());
		
		add(comp);
	}

	public SimplestModuleController getController() {
		return controller;
	}

	public void loadResultWithInputStrings(List<String> list) {
		comp.setText4TopTextArea(list);
		comp.handle(list);
		
	}

	@Override
	public boolean closeTab() {
		return false;
	}

	@Override
	public void changeToThisTab() {
		
	}


	@Override
	public boolean canImport() {
		return false;
	}

	@Override
	public void importData() {
		
	}

	@Override
	public boolean canExport() {
		return false;
	}

	@Override
	public void exportData() {
		
	}

	@Override
	public String[] getFeatureNames() {
		return new String[] {"Present back mutations in text"};
	}
	
	@Override
	public IInformation getModuleInfo() {
		IInformation iInformation = new IInformation() {

			@Override
			public String getWhatDataInvoked() {
				return "The data is loading from the import dialog.";
			}

			@Override
			public String getSummaryOfResults() {
				return "The text presentation of back mutations is generated by the eGPS software.";
			}
		};
		return iInformation;
	}

	@Override
	protected void initializeGraphics() {
		IndependentModuleLoader loader = (IndependentModuleLoader) this.moduleLoader;
		if (loader.list != null) {
			loadResultWithInputStrings(loader.list);
		}
		
	}

}

