package module.multiseqview;

import java.awt.BorderLayout;

import javax.swing.JScrollPane;

import egps2.utils.common.util.SaveUtil;
import egps2.frame.ModuleFace;
import module.multiseqview.view.IntermediateContainer;
import egps2.modulei.IInformation;
import egps2.modulei.IModuleLoader;

@SuppressWarnings("serial")
public class SequenceStructureViewMain extends ModuleFace {

	private SequenceStructureViewController sequenceStructureViewController;
	private IntermediateContainer sequenceStructureViewContainer;

	private ImportDataHander importDataHander = new ImportDataHander(this);

	protected SequenceStructureViewMain(IModuleLoader moduleLoader) {
		super(moduleLoader);
		sequenceStructureViewController = new SequenceStructureViewController(this);
		sequenceStructureViewContainer = new IntermediateContainer(sequenceStructureViewController);

		sequenceStructureViewController.setSequenceStructureViewContainer(sequenceStructureViewContainer);

		setLayout(new BorderLayout());
		add(sequenceStructureViewContainer, BorderLayout.CENTER);

	}

	public SequenceStructureViewController getController() {
		return sequenceStructureViewController;
	}

	public JScrollPane getPaintingPanelJScrolPanel() {
		return sequenceStructureViewContainer.getjScrollPane();
	}

	@Override
	public boolean canImport() {
		return true;
	}

	@Override
	public void importData() {
		importDataHander.doUserImportAction();
		invokeTheFeatureMethod(0);
	}

	@Override
	public boolean canExport() {
		return true;
	}

	@Override
	public void exportData() {
		new SaveUtil().saveData(sequenceStructureViewContainer.getPaintingPanel());
	}

	@Override
	public String[] getFeatureNames() {
		return new String[] { "multi-sequences feature plot" };
	}

	@Override
	protected void initializeGraphics() {

	}

	@Override
	public IInformation getModuleInfo() {
		IInformation iInformation = new IInformation() {

			@Override
			public String getWhatDataInvoked() {
				return "The data is loading from the import dialog.";
			}

			@Override
			public String getSummaryOfResults() {
				return "The multiple sequence structs are generated by the eGPS software.";
			}
		};
		return iInformation;
	}
}
